name: CI
on:
  push:
    branches: [ "develop", "main"]
  pull_request:
    branches: [ "main", "develop"]
  workflow_dispatch:

jobs:
  api-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        version: [16.x, 17.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Dependencies vulnerabilities
        run: npm audit

      - name: Initialization
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Unit tests
        run: npm run test:unit